# Generated by Django 2.2.7 on 2019-12-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('iso_code', models.CharField(max_length=3, verbose_name='ISO Code')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сost')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.Currency', verbose_name='Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.ProductProvider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('can_attach_to_user', models.BooleanField(default=False, help_text='Set it if this account can be attach to user', verbose_name='Can attach to user')),
                ('accessible_by', models.ManyToManyField(blank=True, help_text='Who can access accounts to incoming/outgoing transactions and can see balance', related_name='accessible_accounttypes', to='auth.Group', verbose_name='Accessible by')),
                ('visible_by', models.ManyToManyField(blank=True, help_text='Who sees accounts in outgoing transactions', related_name='visible_accounttypes', to='auth.Group', verbose_name='Visible by')),
            ],
            options={
                'verbose_name': 'Account type',
                'verbose_name_plural': 'Account types',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.AccountType', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Balance')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='finances.Account', verbose_name='Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.Currency', verbose_name='Currency')),
            ],
            options={
                'unique_together': {('account', 'currency')},
            },
        ),
    ]
