# Generated by Django 2.2.7 on 2019-12-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('surcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Surcharge')),
                ('type', models.CharField(choices=[('buy', 'Купівля'), ('sale', 'Продаж')], default='sale', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_refund', models.BooleanField(default=False)),
                ('account_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance', to='finances.AccountBalance')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='finances.Currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='finances.Product')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('sent_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
