# Generated by Django 2.2.7 on 2019-12-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sent_by',
            new_name='sent_to',
        ),
    ]
